merefield/discourse-chatbot

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot.rb
* Utilises existing unused setting
* Fixes a pair of translations.
> FEATURE: Add working model temperature setting

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot.rb
- lib/discourse_chatbot/message/message_prompt_utils.rb
- lib/discourse_chatbot/post/post_prompt_utils.rb
- plugin.rb
* FEATURE: ability to specify a custom model name (so long as it exists in Open AI model namespace)
* IMPROVE: Increase maximum look-behind option so admins can take advantage of bigger contexts of newer models
* COMPATIBILTY: Add a couple of newer popular models to default options (GPT4, GPT3.5-16k)
> FEATURE: permit use of custom model name, add GPT-4, GPT-3.5 16k options

- README.md
- app/jobs/regular/chatbot_reply_job.rb
- plugin.rb
* Function capability is included in the mainline models now, so no need to block agent mode in those instances.
> IMPROVE: Remove now redundant 0613 agent restriction

- plugin.rb
> Update openai gem to latest

- app/jobs/regular/chatbot_reply_job.rb
- lib/discourse_chatbot/post/post_reply_creator.rb
- plugin.rb
> FIX: temp removal of attempt to show reply indicator on public topics

- app/jobs/regular/chatbot_reply_job.rb
- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_agent.rb
- lib/discourse_chatbot/post/post_reply_creator.rb
- lib/discourse_chatbot/reply_creator.rb
- plugin.rb
- spec/lib/bot/open_ai_agent_spec.rb
EXPERIMENTAL: optionally expose some inner workings of bot in agent mode in PMs.
> FEATURE: Add optional inner thought output in PMs (EXPERIMENTAL)

- assets/javascripts/discourse/components/chatbot-launch.hbs
- assets/javascripts/discourse/components/chatbot-launch.js
- assets/stylesheets/common/chatbot_common.scss
- assets/stylesheets/mobile/chatbot_mobile.scss
- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
* Choose icon, or simply use the bot user's avatar 🤖 ☎️ 💻 🧸
> FEATURE: add ability to customise quick launch avatar

- assets/javascripts/discourse/connectors/category-custom-settings/set-chatbot.hbs
- assets/javascripts/discourse/connectors/category-custom-settings/set-chatbot.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/discourse_chatbot/post/post_evaluation.rb
- lib/discourse_chatbot/post/post_prompt_utils.rb
- plugin.rb
- spec/lib/post/post_prompt_utils_spec.rb
* FEATURE: Adds a new Category Setting that allows you to inject a hidden prompt into auto-responding bot posts when this behaviour is set for a specific Category
> FEATURE: ability to inject Category specific prompt for auto-response

- app/jobs/regular/chatbot_topic_title_embedding.rb
- app/jobs/regular/chatbot_topic_title_embedding_delete.rb
- app/models/discourse_chatbot/topic_embeddings_bookmark.rb
- app/models/discourse_chatbot/topic_title_embedding.rb
- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20230820010103_create_chatbot_embeddings_table.rb
- db/migrate/20231026010109_create_new_chatbot_post_embeddings_table.rb
- db/migrate/20240412010101_create_chatbot_topic_title_embeddings_table.rb
- db/migrate/20240412010103_create_chatbot_topic_embeddings_bookmark_table.rb
- db/migrate/20240412010105_create_cosine_pg_vector_chatbot_topic_title_embeddings_index.rb
- lib/discourse_chatbot/embedding_completionist_process.rb
- lib/discourse_chatbot/embedding_process.rb
- lib/discourse_chatbot/functions/forum_search_function.rb
- lib/discourse_chatbot/post/post_embedding_process.rb
- lib/discourse_chatbot/topic/topic_title_embedding_process.rb
- lib/tasks/chatbot.rake
- plugin.rb
- spec/lib/embedding_completionist_process_spec.rb
* FEATURE: if `chatbot_forum_search_function_include_topic_titles` is set, the search function will always return Topic results to the bot and include Topics with good Title matches.
> FEATURE: topic title embeddings and semantic title search

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/functions/forum_search_function.rb
- plugin.rb
- spec/lib/bot/open_ai_agent_spec.rb
- spec/lib/functions/forum_search_function_spec.rb
* LLM can sometimes hallucinate a URL that does not exist
* integrity checks help avoid this
> FEATURE: add url integrity check for search

- lib/discourse_chatbot/message/message_evaluation.rb
- lib/discourse_chatbot/message/message_reply_creator.rb
- lib/discourse_chatbot/post/post_evaluation.rb
- lib/discourse_chatbot/post/post_reply_creator.rb
- lib/discourse_chatbot/reply_creator.rb
- plugin.rb
* Humans change their minds, discard messages being worked on if interrupted (private only).
> FEATURE: Discard messages if interrupted in private

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot_base.rb
- plugin.rb
* You can now elect to log only API calls & responses to logs
* You can now elect to pass progress and/or API calls into warning level logs so they can be viewed in Production
> FEATURE: enhanced logging for Production

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/functions/web_crawler_function.rb
- plugin.rb
EXPERIMENTAL: add a web crawler function using https://www.firecrawl.dev/
> FEATURE: add a web crawler function

- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/post/post_reply_creator.rb
- plugin.rb
Currently JSON results in Inner Thought Posts are not very easy to read.   Here's a significant improvement.
> IMPROVE: make presentation of inner thoughts in Posts prettier

- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/message/message_evaluation.rb
- plugin.rb
> FIX: various fixes

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/functions/web_crawler_function.rb
- plugin.rb
… to help prevent token limit breach
> IMPROVE: add char limit setting for web crawler response

- lib/discourse_chatbot/message/message_evaluation.rb
- lib/discourse_chatbot/message/message_prompt_utils.rb
- lib/discourse_chatbot/message/message_reply_creator.rb
- lib/discourse_chatbot/reply_creator.rb
- plugin.rb
* FEATURE: Adds Chat Thread support - the bot context will be limited to the current Thread.
> FEATURE: add Chat thread support

- .github/FUNDING.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/message/message_prompt_utils.rb
- lib/discourse_chatbot/post/post_prompt_utils.rb
- plugin.rb
* FEATURE: Add additional reasoning models, notably `o3-mini`
* FEATURE: Support RAG for reasoning models (currently, just `o3-mini`)
* FIX: allow user to discuss images generated by the bot
> 1.4.7 Maintenance Release

- config/locales/client.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot_base.rb
- lib/discourse_chatbot/bots/open_ai_bot_basic.rb
- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- plugin.rb
- spec/lib/bot/open_ai_agent_spec.rb
* FEATURE: add `o3` an `o4-mini` reasoning models
* FEATURE: add setting `chatbot_open_ai_model_reasoning_level` to influence amount of reasoning (reasoning models only).
> FEATURE: add new o3/o4 reasoning models and reasoning effort setting

- config/locales/server.en.yml
- config/settings.yml
- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/functions/paint_function.rb
- plugin.rb
* FEATURE: add support for new `gpt-image-1` frontier image generation model
* FEATURE: if tracking by token quota, use actual token usage reported by API (`gpt-image-1`) only.
* Convert paint handling to use base64 data so we can support the new model
> FEATURE: add new image gen model support

- config/locales/server.en.yml
- lib/discourse_chatbot/bots/open_ai_bot_rag.rb
- lib/discourse_chatbot/functions/paint_edit_function.rb
- lib/discourse_chatbot/functions/paint_function.rb
- lib/discourse_chatbot/message/message_prompt_utils.rb
- lib/discourse_chatbot/post/post_prompt_utils.rb
- plugin.rb
* FEATURE: edit the last image interactively via your prompting
* requires new `gpt-image-1` frontier image generation model and for access you need to be verified with OpenAI.
* FEATURE: by way of a refactor, pdf reading support has been added to Chat.
> FEATURE: edit a picture interactively

- app/controllers/discourse_chatbot/chatbot_controller.rb
- assets/javascripts/discourse/components/chatbot-launch.hbs
- assets/javascripts/discourse/components/chatbot-launch.js
- assets/javascripts/discourse/initializers/chatbot-post-launch-init.js
- assets/stylesheets/common/chatbot_common.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- plugin.rb
* EXPERIMENTAL: kick off a chat with Chatbot from any Post behind setting `chatbot_quick_access_bot_post_kicks_off`
> FEATURE: kick off chat with bot from a Post

- assets/javascripts/discourse/components/chatbot-launch.hbs
- assets/javascripts/discourse/components/chatbot-launch.js
- assets/javascripts/discourse/initializers/chatbot-post-launch-init.js
- assets/stylesheets/common/chatbot_common.scss
- config/settings.yml
- plugin.rb
* IMPROVE: Post launch button moves the the Post Button Menu
* IMPROVE:  Chat kick-off message location and overrides refined.
* IMPROVE: Annoying console warning removed.
* IMPROVE: styling - there is now once again, only one `chatbot-btn` id 😊
> IMPROVE: Post launch improvements
